language: generic
services: 
  - docker
  
before_install: 
  -docker build -t kellydouglass/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kellydouglass/docker-react npm run test -- --coverage